/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.samplejsonws.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SampleAsset service. Represents a row in the &quot;JSONWS_SampleAsset&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.samplejsonws.model.impl.SampleAssetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.samplejsonws.model.impl.SampleAssetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SampleAsset
 * @see com.liferay.samplejsonws.model.impl.SampleAssetImpl
 * @see com.liferay.samplejsonws.model.impl.SampleAssetModelImpl
 * @generated
 */
public interface SampleAssetModel extends BaseModel<SampleAsset> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sample asset model instance should use the {@link SampleAsset} interface instead.
	 */

	/**
	 * Returns the primary key of this sample asset.
	 *
	 * @return the primary key of this sample asset
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sample asset.
	 *
	 * @param primaryKey the primary key of this sample asset
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the asset ID of this sample asset.
	 *
	 * @return the asset ID of this sample asset
	 */
	public long getAssetId();

	/**
	 * Sets the asset ID of this sample asset.
	 *
	 * @param assetId the asset ID of this sample asset
	 */
	public void setAssetId(long assetId);

	/**
	 * Returns the user ID of this sample asset.
	 *
	 * @return the user ID of this sample asset
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this sample asset.
	 *
	 * @param userId the user ID of this sample asset
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sample asset.
	 *
	 * @return the user uuid of this sample asset
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this sample asset.
	 *
	 * @param userUuid the user uuid of this sample asset
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this sample asset.
	 *
	 * @return the name of this sample asset
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this sample asset.
	 *
	 * @param name the name of this sample asset
	 */
	public void setName(String name);

	/**
	 * Returns the date of this sample asset.
	 *
	 * @return the date of this sample asset
	 */
	public Date getDate();

	/**
	 * Sets the date of this sample asset.
	 *
	 * @param date the date of this sample asset
	 */
	public void setDate(Date date);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SampleAsset sampleAsset);

	public int hashCode();

	public CacheModel<SampleAsset> toCacheModel();

	public SampleAsset toEscapedModel();

	public String toString();

	public String toXmlString();
}